os: linux
dist: bionic

language: cpp
compiler:
  - clang

arch:
  - amd64
  - arm64

services:
  - mysql

script:
  - $CXX --version
  - mysql -V
  - mysql -uroot < sql/create_mysql.sql
  - mysql -utrial -ptrial doit < sql/create_database.sql
  - mysql -uroot < sql/drop_mysql.sql
